<?php

namespace AppBundle\Repository;

/**
 * SeenBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeenBetRepository extends \Doctrine\ORM\EntityRepository
{
}
