<?php

namespace AppBundle\Repository;

/**
 * SinglePayBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinglePayBetRepository extends \Doctrine\ORM\EntityRepository
{
}
