<?php

namespace AppBundle\Repository;

/**
 * UserBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBetRepository extends \Doctrine\ORM\EntityRepository
{
}
