api:
    resource: '@AppBundle/Controller/Api'
    type: annotation
admin:
    resource: '@AppBundle/Controller/Admin'
    type: annotation
home:
    resource: '@AppBundle/Controller/'
    type: annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
