# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    serialize_manager:
        class:        AppBundle\Utils\SerializeManager
        arguments:    ['@service_container']
    security_view_bet_manager:
        class:        AppBundle\Utils\SecurityViewBetManager
        arguments:    ['@service_container']